coreset:
  preset: dino_features
coreset_config_file: src/configs/coreset_configs/coreset_config.yaml
batch_size: 16
num_workers: 4
subsample:
  use_subsample: false
  fraction: 0.1
  threshold: 5000000
encoder: dino
dataset_params:
  size:
  - 512
  - 512
  downsample_flow: 32
  max_kps: null
  dense_kps_use_all: true
  verbose: false
  debug: false
  normalize_images: false
  kitti_val_use_full_training: true
dataset_overrides:
  spair:
    datapath: ./models/Datasets_CATs
    normalize_images: false
  synthetic:
    geometry_config_path: src/configs/online_synth_configs/OnlineGeometryConfig.yaml
    processor_config_path: src/configs/online_synth_configs/OnlineProcessorConfig.yaml
    normalize_images: false
    device: cuda
datasets:
- mixed: true
  name: spair_synthetic_30_70
  datasets:
  - spair
  - synthetic
  percentages:
  - 0.3
  - 0.7
  split: train
  representation: dino
  num_batches: 100
  is_eval: false
  output: coresets/spair_synthetic_30_70_train_dino.pt
- mixed: true
  name: spair_synthetic_50_50
  datasets:
  - spair
  - synthetic
  percentages:
  - 0.5
  - 0.5
  split: train
  representation: dino
  num_batches: 100
  is_eval: false
  output: coresets/spair_synthetic_50_50_train_dino.pt
- mixed: true
  name: spair_synthetic_70_30
  datasets:
  - spair
  - synthetic
  percentages:
  - 0.7
  - 0.3
  split: train
  representation: dino
  num_batches: 100
  is_eval: false
  output: coresets/spair_synthetic_70_30_train_dino.pt
- mixed: true
  name: pointodyssey_synthetic_30_70
  datasets:
  - pointodyssey
  - synthetic
  percentages:
  - 0.3
  - 0.7
  split: train
  representation: dino
  num_batches: 100
  is_eval: false
  output: coresets/pointodyssey_synthetic_30_70_train_dino.pt
- mixed: true
  name: pointodyssey_synthetic_70_30
  datasets:
  - pointodyssey
  - synthetic
  percentages:
  - 0.7
  - 0.3
  split: train
  representation: dino
  num_batches: 100
  is_eval: false
  output: coresets/pointodyssey_synthetic_70_30_train_dino.pt
- mixed: true
  name: flyingthings_synthetic_30_70
  datasets:
  - flyingthings
  - synthetic
  percentages:
  - 0.3
  - 0.7
  split: train
  representation: dino
  num_batches: 100
  is_eval: false
  output: coresets/flyingthings_synthetic_30_70_train_dino.pt
- mixed: true
  name: flyingthings_synthetic_70_30
  datasets:
  - flyingthings
  - synthetic
  percentages:
  - 0.7
  - 0.3
  split: train
  representation: dino
  num_batches: 100
  is_eval: false
  output: coresets/flyingthings_synthetic_70_30_train_dino.pt
- mixed: true
  name: sintel_synthetic_30_70
  datasets:
  - sintel
  - synthetic
  percentages:
  - 0.3
  - 0.7
  split: train
  representation: dino
  num_batches: 100
  is_eval: false
  output: coresets/sintel_synthetic_30_70_train_dino.pt
- mixed: true
  name: sintel_synthetic_70_30
  datasets:
  - sintel
  - synthetic
  percentages:
  - 0.7
  - 0.3
  split: train
  representation: dino
  num_batches: 100
  is_eval: false
  output: coresets/sintel_synthetic_70_30_train_dino.pt
